### ISSUE TITLE
User can hit submit on thread form without applying last tag typed in tag field

### ISSUE THREAD

**Issue by lovethecoat51** [blackjackkent/RPThreadTrackerV3.FrontEnd#10]
WELL I was trying to get some screencaps for the problem I was talking about - but I've encountered a different problem.

I tried to add a tag to one of my threads and it says that it updated it and everything, but it doesn't seem to actually save it. When I open up the thread info again, the tag isn't there.

**Comment by blackjackkent** [comment]
Hmm -- I have a suspicion what the problem might be here but I'm not positive. Did you add only one tag, and if so, did you hit submit for the thread immediately rather than hitting comma?

**Comment by lovethecoat51** [comment]
....okay yeah that solved it LOL sorry about that!! I'll go get the screencaps for that other problem I mentioned now

**Comment by blackjackkent** [comment]
Nothing to be sorry for -- this is actually a bug and something I should address, cos you're likely not the only person who will try to do that. So thank you very much! (Please create a separate issue for the other problem you mentioned, so I can track this problem on this one.)

**Comment by lovethecoat51** [comment]
Will do! Thank you!

**Comment by blackjackkent** [comment]
OK, I *believe* I have fixed this behavior; you should see the added tag even if you hit submit without hitting comma to confirm a single tag. Let me know if your original use case works as expected now!

**Comment by lovethecoat51** [comment]
YES it works now with the way I was originally doing! Thank you!

**Comment by blackjackkent** [comment]
Perfect. Thank you so much for catching this! :)
