### ISSUE TITLE
All Threads page

### ISSUE THREAD

**Issue by Siriuslychessi** [blackjackkent/RPThreadTrackerV3.FrontEnd#12]
There is an "All Threads" page that I personally find useful to see how many threads I have going on with which partner, but in the new version there doesn't seem to be one. Don't know if it's on purpose or not, maybe other people don't find it as useful?

**Comment by blackjackkent** [comment]
I was going back and forth on whether to include it in the new version or not; it's not super difficult to add back in so I will look at returning it to the site structure. :)

**Comment by blackjackkent** [comment]
I have updated the beta site to include the "All Threads" page again; please let me know if everything behaves as you would expect! :) Thanks!
