### ISSUE TITLE
Refresh button issue

### ISSUE THREAD

**Issue by FenPat** [blackjackkent/RPThreadTrackerV3.FrontEnd#13]
The refresh button seems to glitch out of the box it was intended to fit in.  I'm not sure if it was because of that, but prior to noticing I had re-sized the browser window to fit it against another one. Maybe the sudden change in size glitched it out of its box? But I tried making it take up the full screen again as well as refresh the page without using the button, and it's still like that, so I'm not sure if I was the one to cause it. Hope the description makes sense.
-My tracker username is FenPat!

**Comment by blackjackkent** [comment]
Thanks for the heads up! Will look into this. :)

**Comment by blackjackkent** [comment]
This should be resolved now; let me know if the behavior seems a little bit cleaner. :) Thanks!

**Comment by FenPat** [comment]
It looks super neat! :D And seems to be functioning perfectly :3 Awesome!

**Comment by blackjackkent** [comment]
Awesome, thanks so much for following up! :)
