### ISSUE TITLE
Update help contact form to redirect to new GitHub issue

### ISSUE THREAD

**Issue by blackjackkent** [blackjackkent/RPThreadTrackerV3.FrontEnd#144]
## Expected Behavior
When navigating to the "Contact Me" section of the "Help" screen, the user should be prompted to navigate to GitHub and create an issue here instead.

## Current Behavior
"Contact Me" section currently triggers an email to me, which is logic that can be removed with the implementation of this change.

## Context
By moving user questions/suggestions/bug reports to GitHub, they can be addressed by other contributors as well.

**Comment by Niaz-Ul-Haque** [comment]
Can I try to deal with this issue? WIll be a great practice for me and I am super interested in this.

**Comment by blackjackkent** [comment]
Go for it! :)

**Comment by Niaz-Ul-Haque** [comment]
Thank you for the opportunity, Ill dive straight onto this during weekedns. Thank you!

**Comment by Niaz-Ul-Haque** [comment]
[#147](https://github.com/blackjackkent/RPThreadTrackerV3.FrontEnd/pull/147)
