### ISSUE TITLE
Not tracking new threads

### ISSUE THREAD

**Issue by r-seaworld** [blackjackkent/RPThreadTrackerV3.FrontEnd#159]
## Expected Behavior
 Need to track new threads

## Current Behavior
 Not tracking new threads from the past two weeks, but tracking older ones fine. 

## Possible Solution
 Unsure. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
 Chrome. 
* Browser name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by blackjackkent** [comment]
Hello! I've been looking into this and haven't been able to reproduce it, nor have I had any other reports of it from other users.

Can you tell me more about the issue? Are you seeing an error message when trying to track a new thread?

**Comment by blackjackkent** [comment]
Closing since I never heard back from OP. Happy to look further into this if further info is provided, though!
