### ISSUE TITLE
Can you add jcink to this?

### ISSUE THREAD

**Issue by lissita** [blackjackkent/RPThreadTrackerV3.FrontEnd#160]
Curious if you could add jcink servers to this? I really like the concept and would be nice! :D 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by blackjackkent** [comment]
Hey!

I've heard a little bit about jcink as being another currently popular platform for RPing. Unfortunately, it doesn't look like jcink has any sort of official API (application programming interface) like Tumblr does that I can make use of to retrieve info about people's activities there. So at the moment i don't think it's going to be easily possible to integrate it with RPThreadTracker. 

I do appreciate the suggestion, though! And I will be keeping an eye out to see if further developments make this more feasible in the future.
