### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by ScreeC** [blackjackkent/RPThreadTrackerV3.FrontEnd#162]
## Expected Behavior
Adding a new thread gets added to thread tracker

## Current Behavior
Thread appears as "invalid date", both when added manually and through an extension

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Windows Google Chrome, both on laptop and PC

**Comment by blackjackkent** [comment]
Hello! I'm so sorry; for some reason GitHub never sent me a notification for this issue. Thanks so much for letting me know about this; I definitely want to look into it.

However, I am not able to reproduce this bug on my end. Could you send me more info about specific thread info that you used and got this result, so I can test with that exact data? If you don't want to post it here, you can send me an email at rosalind@blackjack-software.com with the info. :)

Thanks!

**Comment by blackjackkent** [comment]
Closing this as I never heard anything further, but please feel free to open another issue if you want to follow up!
