### ISSUE TITLE
Small Thing- :)

### ISSUE THREAD

**Issue by lyrieux** [blackjackkent/RPThreadTrackerV3.FrontEnd#171]
No issues yet found! All is running much more smoothly and far faster- you've done AMAZING! 

The only thing I miss from the tracker that isn't in the beta of the new version is the ability to click a thread and for the row to turn a different colour/tone. Usually, when I do my replies, I select all the threads I have replied to/queues as I go and then do it by bulk action - but the only indicator that a thread is selected now is the little tick-box on the far side.  Even if the change wasn't as much of a colour change, perhaps just a few tones darker/lighter would really help visually with knowing what you have/have not got selected.

:) 

I also just wanted to thank you for not giving up on the project, and for continuing to be really sensational! You've made a tool that I know so so many use and that many couldn't do without - and I cannot thank you enough for your efforts <3 !

**Comment by blackjackkent** [comment]
Hey! Thanks so much for this feedback and the testing; I'm glad to hear that things feel a little snappier! I will definitely work on a fix regarding the row highlighting. :) That's a great note.

And thank *you* for your support! <3

**Comment by lyrieux** [comment]
ooO; I am still having a small issue where I mark multiple threads as queued, one or two end up not actually being marked and I have to do it again?

**Comment by blackjackkent** [comment]
I've pushed an update that should add the row highlighting you're talking about. :) Let me know if all looks good, when you have a chance!
