### ISSUE TITLE
Bulk Adding to Queue

### ISSUE THREAD

**Issue by lyrieux** [blackjackkent/RPThreadTrackerV3.FrontEnd#172]
Hi hi! 

Say I was marking three threads to be queued, and submit them through the bulk actions ability, maybe only one of the three will actually be marked as queued. I have to do the other two again, usually one at a time, for them to be marked. 

:) x

**Comment by blackjackkent** [comment]
Hello! Thanks so much for this feedback, good to know. 😄  Is this happening on the production site or just the beta test one?

**Comment by lyrieux** [comment]
Oddly enough - - both xD

**Comment by blackjackkent** [comment]
OK, I will look into it. Thank you! :)

**Comment by blackjackkent** [comment]
Hmm. I am not able to reproduce this on my end. Could you possibly do either of the following (or both if it's possible/convenient):

- Send me a screen recording of you encountering the issue.
- Reproduce the issue again, and once you see the error, follow the instructions on this site https://screenful.com/how-to-open-the-browser-console to open the Javascript console for whatever your browser is? In that console, you should see a bunch of error logs; can you just copy whatever it says and send that to me? (Particularly anything that is in red.)

Thanks!

**Comment by lyrieux** [comment]
Hi! 
I've managed to get a recording! I marked three threads to be queued, selected them, and when the tracker reloaded, only one of them had been sent to queued. I made sure my browser was up to date, too, just in case I was simply being a tit. I uploaded it to youtube for you, [here](https://www.youtube.com/watch?v=QO8fhkaB3bM). This was on the beta version, but the same happens on the other, too. 

And here's the errors that popped up :) - I hope this helps :) 


Failed to load resource: the server responded with a status of 401 (Unauthorized)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/thread?isArchived=false:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/profilesettings:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/character:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
Simple-Line-Icons.0cb0b9c589c0624c9c78dd3d83e946f6.woff2:1          Failed to load resource: the server responded with a status of 404 (Not Found)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/thread/1756847:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/thread/1769047:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
rpthreadtrackerv3-backend-staging.azurewebsites.net/api/thread/1724489:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by blackjackkent** [comment]
Well, that's really baffling. :P I honestly have no idea what's going on because those error messages didn't have the answer I was hoping for and the video looks exactly like what I'm doing on my end. 🤔

How consistently are you able to reproduce this problem? I wonder if you'd be willing to maybe get on a Zoom call and screenshare so I can take a closer look at what's going on. (No pressure if not, though; I'm just a little stumped!)

**Comment by lyrieux** [comment]
How wild, omg. Once I'm home, (and have actually written some replies-) I'll turn off all of the little extensions I have on my browser to make sure its none of them interfering? I've no idea if thats a possibility- but I'll give it a go to make sure I'm not being daft first aha. Tbh, the only ones I have is stylish and one that changes the tumblr font bc it hurts my eyes, aha! So I'm not sure if those (or xkit for that matter) would make any issue? I'd say not, but then I'm clueless when it comes to coding stuff, aha-! 

I can reproduce this problem every time; if I select, say, 8 replies to be queued from various blogs - maybe only one or two will actually be marked as queued, and its usually the first one I select. The others I then have to do manually otherwise they just don't get marked.

**Comment by blackjackkent** [comment]
Hm. Super weird. I can't see why any of those extensions would make a difference but yeah testing without them just to see is a good idea.

Yeah, if you can reproduce it that consistently then I'd love to get on a screenshare call with you to be able to look more closely at what's going on. (Again, no pressure! But let me know. :smile:)

**Comment by lyrieux** [comment]
Hi! Just to double check, I turned off every single extension on my browser and the queueing issue still happened. Weirdly aha.  (i even tested it on my sisters PC and it did the same thing, I thought it might have just been me aha-)

And sure, I can do that :) Just lemme know what times are good for you and we can figure something out :)

**Comment by blackjackkent** [comment]
Sounds good! Can you give me a ping at rosalind@blackjack-software.com - we can discuss scheduling there. Thanks!
