### ISSUE TITLE
Public Thread View - Visual Fix

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#18]
This is just a minor design issue.  I'm playing around with 'Manage Public Views' and noticed that the title doesn't seem to be aligning properly up at the top on the right.

![rpthreadtracker-publictracker](https://user-images.githubusercontent.com/41037873/42659741-c9ecebcc-85ee-11e8-8790-34578dba73b3.jpg)

Tracker Username: purpledragonrp

**Comment by blackjackkent** [comment]
Aha, good catch; will get this fixed ASAP. Thank you! :)

**Comment by blackjackkent** [comment]
Upon closer examination there was a lot of weird stuff going on with that page (especially on smaller screen sizes). :P I've made some visual updates which should improve the experience; let me know if things look more as expected now!

Thanks!
