### ISSUE TITLE
Public Thread View - Archived Posts Not Showing Up

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#19]
So, first I want to start by saying I LOVE that the public Thread View has become a customize-able feature!  I'm still playing with things, and I noticed on the creation of my first public view that, even though I clicked off on all four boxes to show My Replies and Their Replies and Archived Threads and Queued Threads, the archived threads don't appear to be showing up.

I've only made the one Public View, so far, and I'm happy to test and see if the issue persists on the others I create, but I wanted to make you aware.

Tracker Username: purpledragonrp

**Comment by blackjackkent** [comment]
Yikes, that's a good catch. I will look into this and let you know when the fix is ready to be tested. :) Thank you!

**Comment by blackjackkent** [comment]
OK, I've pushed a fix that resolves this issue! Please let me know if everything behaves as expected, or if you run into any more issues. :) Thanks so much for catching this!

**Comment by purpledragon42** [comment]
I'm definitely seeing the archived threads now.  Thank you!  I have an additional question about the Public Thread view, though, now that they're showing up.

Is there any way that the last reply dates and links to the last poster could be preserved for the archived threads?  I actually keep all of my open starters in my archive to keep them from causing confusion in regards to the number of active replies I owe.  So, it would be useful to have links to them for anyone who's interested in starting something new.  In addition, if anyone is looking for an old thread they're wanting to restart, having links to my last reply easily accessible to them would be fantastic.  Thank you so much!
