### ISSUE TITLE
Thread Table Filtering Does Not Distinguish Between Characters On the Same Blog

### ISSUE THREAD

**Issue by minixmousy** [blackjackkent/RPThreadTrackerV3.FrontEnd#2]
tracker user: minniemouse
blog in question: animusdeviance

i have three characters on this blog. when i select "animusdeviance (Ann Takamaki)" it functions mostly as expected and pulls up every thread tracked for Ann Takamaki...as well as my other threads on that blog that i've retracked. in the character bar is "animusdeviance (Ann Takamaki)"

when i try to select either Junko Enoshima or Kara (both on the same blog) it behaves exactly as if i'd clicked the former. selecting any other blog brings up only those threads.

**Comment by minixmousy** [comment]
going to add here that i'm going to try wiping all my threads & characters on the beta account and see if i can replicate it after starting fresh

**Comment by minixmousy** [comment]
it persists even if you've started fresh

**Comment by blackjackkent** [comment]
Aha. I def know what the problem is here. :) Should have a fix soon. Thank you!

**Comment by blackjackkent** [comment]
I have pushed an update to fix this and it should be resolved on the V3 beta site now. Please let me know if things are behaving more as you expect! Thanks. :)

**Comment by minixmousy** [comment]
it's working right for me now! thank you so much ^^

**Comment by blackjackkent** [comment]
Sweet! Thank you for reporting the issue! :)
