### ISSUE TITLE
Suggestion: Public Views

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#21]
Would there be some way, when using multiple 'Public View' list options, to have the public view differentiate between the current RPs, queued RPs, and archived RPs?  Either an additional column that would specify where they're located?  Or a drop down menu so public viewers could filter things if they wanted/needed to?  Just something to quickly and easily help viewers know which is which?

**Comment by blackjackkent** [comment]
This is definitely a good idea; I will probably go with the dropdown idea. I'll let you know when this has been implemented! Thanks. :)

**Comment by blackjackkent** [comment]
Hey -- I added a dropdown menu on the public view to allow filtering by the state of each thread; let me know if the behavior seems intuitive or if you have any further thoughts. :) Thanks for the suggestion!

**Comment by purpledragon42** [comment]
My apologies - I'm only just now seeing your reply.  It works and looks great on my end.  Thank you so much!  :)

**Comment by blackjackkent** [comment]
Awesome, thanks for following up! :)
