### ISSUE TITLE
Thread Creation Fails When Character Dropdown Is Not Modified

### ISSUE THREAD

**Issue by pixiegaga** [blackjackkent/RPThreadTrackerV3.FrontEnd#24]
username: pixiegaga

On the 'your chaacters' box that shows the threads of each character you have, one of them doesn't appear, I have 2 threads going on a character and it says that I only have 1. I went to check to 'all threads' to see if there was some information I hadn't entered, I edited the thread information and went to the dashboard again, it still shows 1 even though I'm tracking 2.

**Comment by blackjackkent** [comment]
Hmm. Could you shoot me an email (or reply here if you're comfortable) with the URL of the blog that is misbehaving? That will help me nail down why it's not showing up.

Thanks!

**Comment by blackjackkent** [comment]
We determined by email that the issue is that the thread creation fails if the user has not changed the character dropdown. (I thought this issue was fixed but I guess not. >.< ) 

Will update when I've fixed the problem.

**Comment by blackjackkent** [comment]
I've updated the thread creation modal so that it doesn't select a character by default; this should eliminate this issue going forward. :) Thanks for catching it!
