### ISSUE TITLE
Filter By Tag

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#25]
A few of my threads include tags i.e 'text' & 'smut' but when I go to filter the tags nothing happens. This only seems to happen when I'm on 'All Threads' but works fine in 'Your Turn' & 'Their Turn'

**Comment by blackjackkent** [comment]
That's weird. :O I will work on getting that fixed right away; thanks for the heads-up!

**Comment by blackjackkent** [comment]
OK, this issue should now be resolved! Please let me know if everything's behaving as you expect. :) Thanks so much!

**Comment by glcryxdays** [comment]
Looks great, thank you very much.
