### ISSUE TITLE
Character Sorting

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#27]
When clicking on the title sections (Thread Title, Last Poster, etc) they arrange themselves into a correct order (alphabetically or chronologically, or reversed versions of those) but when I click the Character section, it doesn't put it into an order, so to speak. I only have the one blog linked to my threadtracker, but the character names beside the blog url don't match up in alphabetical order.

**Comment by blackjackkent** [comment]
Aha, good catch. Yeah, right now that sorts it by the blog url, but it should probably fall back to the character name for two characters that have the same URL. I will get this fixed ASAP. :)

**Comment by blackjackkent** [comment]
OK, I believe this issue should be resolved! You should see the characters sorting by character name where they have the same URL. :) Please let me know if this is behaving more as you expect now! Thanks!

**Comment by glcryxdays** [comment]
It's working great now, thank you!

**Comment by blackjackkent** [comment]
Awesome! Thank you for the heads up. :)
