### ISSUE TITLE
Public View: Create by Tag

### ISSUE THREAD

**Issue by thenameiskymani** [blackjackkent/RPThreadTrackerV3.FrontEnd#28]
At current, Public Views require you to list characters/blogs that need to be included. But Because I have multiple blogs, I actually tag my threads by fandom. In V1 I was able to just have the public link filter by tag (and then organize as I please) like so: [LINK](https://www.rpthreadtracker.com/public/allthreads?userId=20820&currentBlog=&sortDescending=false&currentOrderBy=UserTitle&filteredTag=Fandom:%20ML). But because of this extra step in Public View, I can't do this so simply. I do believe this to be a mistake, because say I'm writing an AU thread? Nala from the Lion King wouldn't have been selected, so she wouldn't show up in the public link "Fandom: Miraculous Ladybug", even though her _thread_ would've been tagged as such.

**Comment by blackjackkent** [comment]
Hi! Thanks for getting in touch about this!

You do have the option to filter your public view by tag as well as character:

![image](https://user-images.githubusercontent.com/13437011/42969400-b1e05f14-8b6b-11e8-94e0-4fdc4a001c1d.png)

I believe this should be sufficient for your needs -- for the scenario you describe above, you would select all your characters and only the tag "Fandom: Miraculous Ladybug" and you would get all threads with that tag listed in your public view.

Let me know if I'm misunderstanding your meaning. :)

**Comment by thenameiskymani** [comment]
Hello! That was quite prompt!

Yes, so as long as I do them both, your tracker is fine with this:

 

 

But my issue is I want to track by tag alone, and this is where it gets upset:

 

 

I suppose I didn’t do the best job of explaining, but hopefully the screenshots help. 

My suggestion was that you allow the tracker to track by tag alone, because it will account
for situations in which characters that don’t usually write in certain fandoms have threads
For said fandom. And that’s just MY situation, I’m sure there will be others. ^^

 

Best,

 

❤ Ky

**Comment by blackjackkent** [comment]
Hm. Your screenshots didn't come through but I think I understand what you mean, regardless. It sounds like the usability would be improved by having the character selection box work the same way the tag selection box does -- that you can just leave it unselected to include all characters in the public view by default. I'll work on making this update. :)

Thanks for the insight!

**Comment by thenameiskymani** [comment]
Sounds like you understood to me! I’ve properly attached them this just in case, since either way I was gonna reply. Thank you for considering my suggestion! ^///^

 

❤ Ky

**Comment by blackjackkent** [comment]
Hey! I've updated the site so that it allows creating a public view with no tags or characters selected in order to include everything. Let me know if this resolves your issue! :) Thanks.

**Comment by blackjackkent** [comment]
Closing this issue since I haven't heard anything further but feel free to reopen it if you have any other thoughts! :) Thanks!
