### ISSUE TITLE
Select Character

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#29]
When you 'Add New Thread' and go to select a character, it lists them in an unorganized way, that makes it hard to find the character you're in search for, especially when you have a lot of characters.

**Comment by blackjackkent** [comment]
Hmm -- I suspect this is a similar issue to the other one you reported with sorting characters in the table, that it's sorted by blog URL but not character name. I will get that updated so it's more intuitive. :) Thanks!

**Comment by blackjackkent** [comment]
I've updated the behavior of that dropdown so it should sort the characters by both URL and name. Let me know if this seems to be behaving right for you now. Thanks! :)

**Comment by glcryxdays** [comment]
That's great thanks! Maybe could I suggest doing the same with the drop down lists of 'characters', 'last poster' and 'tracked partner' please?

**Comment by blackjackkent** [comment]
Good call -- I've updated the filter dropdowns in the thread table to also be sorted! Let me know if this helps! :) Thanks.

**Comment by glcryxdays** [comment]
Perfect, thank you very much!
