### ISSUE TITLE
Suggestion: Thread Descriptions

### ISSUE THREAD

**Issue by lyrieux** [blackjackkent/RPThreadTrackerV3.FrontEnd#30]
I was just thinking to myself, while observing the way you see tags on V3 [the little dropdown underneath the tracked thread] how good  it would be if there as a little option to do much the same, but instead insert a description of the content of the thread being tracked. I can't be the only one who usually forgets, despite a title, and has to go through to the link in order to remind myself- 

Also; where it shows both the URL of the blog and the character name inserted; perhaps there could be an option to show either the URL or the Character name, or both. I'd like to just have the character name, personally; I know my url haha. 

It really is looking gorgeous already though <3

**Comment by blackjackkent** [comment]
This is a really good idea. I might hold it for a feature to be added after the initial launch since right now I'm prioritizing bugs and changes that affect the overall experience so I can get the new version deployed. But once it's live this would be a relatively simple addition to make and would definitely add value. Thank you for the suggestion! :)

**Comment by blackjackkent** [comment]
Hey! I got efficient and decided to go ahead and implement this now; you should now be able to optionally add a description to the thread and see it displayed in the expandable subcomponent for the table row. Please give it a shot and let me know how things look and if there's any unexpected behavior!

Thanks for the suggestion! :)

**Comment by lyrieux** [comment]
aHHHHH! It looks so good! I love it! Very useful! Awesome!

I’ve also been staring at the tracker for a good while now and I have finally figured out what looks weird to me; the vertical lines between each header and between the thread parts ;(title, url link, character, poster, ect-) Not sure if that would be something you’d be willing to change on a graphic point of view or whatever; for some reason it took me AGES to figure out it was that aha. Theres something about it that edits fluidity.

And hey! Things are really looking good!

________________________________

**Comment by blackjackkent** [comment]
Hmm. I'll have to give some thought to that, since it's also important to have some sort of divider to make it easier to read the table. Thanks for the suggestion. :)

Am going to close this ticket since the particular issue has been addressed. Thank you so much! :D
