### ISSUE TITLE
Suggestion: Alphabetize Lists

### ISSUE THREAD

**Issue by thenameiskymani** [blackjackkent/RPThreadTrackerV3.FrontEnd#33]
It would be extremely helpful if we either had the option to alphabetize lists or if it happened automatically in the following locations:

- The "Manage Characters" Page
- The dropdown lists on all Threads pages:
   -- "Character"
   -- "Last Poster"
   -- "Tracked Partner"
   -- "Filter by Tag"

Every other applicable location seems to already do this. Thank you for your time!

--Ky

**Comment by blackjackkent** [comment]
Hey! Thanks for the suggestions. :) I actually just pushed some code that should address this, so you should see the dropdown lists on the thread tables sorted correctly now.

I'm not sure what you mean about alphebetizing on the "Manage Characters" page though -- you can sort that table by clicking on the headers of each column.

**Comment by blackjackkent** [comment]
Am closing this issue -- feel free to reopen it if you have further info though! :) Thank you for the suggestion!
