### ISSUE TITLE
Marking Threads as Queued

### ISSUE THREAD

**Issue by lovethecoat51** [blackjackkent/RPThreadTrackerV3.FrontEnd#34]
I'm not sure if this has to do with the server or what, but pretty much every time I try to mark a thread as queued (either by using the single button next to the title or by using a bulk action), the page will refresh, I'll get the green message that it has been updated..... and the thread still remains in the "your turn" column. I normally have to mark it as queued at least twice before it actually registers and moves the thread.

**Comment by blackjackkent** [comment]
Hmm. That's very weird, and I'm having trouble reproducing it on my end...is it happening on all thread screens? (Your Turn, Their Turn, Archived, etc?)

**Comment by lovethecoat51** [comment]
It's happening on Your Turn and All Threads - although now it's becoming a bit more intermittent rather than every. single. time. 

However, now when I queued something and it updates my feed, it takes away any filters I had been using (eg by character) and I'm fairly sure it wasn't going that before?

**Comment by blackjackkent** [comment]
Aha -- I suspect I know what the problem is re: queueing. All Threads includes both queued and non-queued threads, so the "Mark Thread Queued" button probably shouldn't be on that table because it's somewhat ambiguous and thus you're expecting the thread to disappear when it's clicked even though it shouldn't. I will fix this and you can let me know if it resolves the issue you're seeing.

You're right that the filter behavior is probably not ideal; I'll work on fixing that as well. Thanks!

**Comment by lovethecoat51** [comment]
It's.... somewhat been resolved? When I click on the queue button (in Your Turn), it queues the thread. But if I select multiple threads and try to bulk action them (still in Your Turn), it's not grabbing all of them. I've only tried it with 2 or 3 threads, but it keeps leaving the last one off (even though the box is ticked).

But the filter is back to what it should be doing!

**Comment by lovethecoat51** [comment]
Okay so I've been messing around with it a little more - it seems like it works as long as I click the queue button once and then let it go. If I get impatient and click again, it doesn't mark it as queued. 

I'll mess around with the bulk action again to see if that's the same.

**Comment by blackjackkent** [comment]
Ah, that definitely makes sense. (The second click is triggering a second request to reverse the thread's status again so the overall effect is that the thread is left unmarked. Probably same deal with bulk.)

I'll have to ponder on the best way to deal with this. :O Very useful report though -- thank you!

**Comment by lovethecoat51** [comment]
I tried again on the bulk actions and it's still not working :( I'm only pressing the button once, and this time, when I tried to bulk queue 5 threads, it managed to get only 1 queued. I DO have over 100 threads being tracked (but not by much, I think it's like 105 threads), so I get that it might slow things down, but surely that can't be the only thing affecting the bulk queueing problem.

**Comment by blackjackkent** [comment]
Hmm. That's extremely weird and I'm not able to reproduce it on my account. Would you mind hitting me up by email with your account information and letting me log in as you and  poke around a bit? I'm curious if this is somehow something account-specific.

**Comment by lovethecoat51** [comment]
Sure thing! I don't know if it makes a difference, but if I click away from the tab (to check my email or something while I'm waiting), that's when it seems to mess up.
