### ISSUE TITLE
Thread Count Per Character

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#35]
On the dashboard, I've noticed there's how many threads each character/muse has, and that's great to see, but maybe it could be put onto the character page too? So that it's a little easier to see and notice too. Thank you.

**Comment by blackjackkent** [comment]
This is an excellent idea and pretty easy to implement; I'll definitely get this done soon. :) Thanks!

**Comment by blackjackkent** [comment]
Hello! I have added this column to the "Manage Characters" page; let me know if everything seems to be working as expected. :) Thanks for the suggestion!

**Comment by glcryxdays** [comment]
Everything looks great, thank you!
