### ISSUE TITLE
New Character

### ISSUE THREAD

**Issue by forgottendestruction** [blackjackkent/RPThreadTrackerV3.FrontEnd#36]
I'd click the 'add new character' and it just refreshed the page.

**Comment by blackjackkent** [comment]
Augh! You are so right. D: Some work I was doing on improving site performance accidentally broke some behaviors -- including that one. I've reverted the changes and things should be behaving as normal now. Thank you for catching this!

**Comment by blackjackkent** [comment]
I'm closing this ticket since I haven't heard anything further regarding this issue but feel free to reopen it or create a new one if you encounter any other issues! :) Thank you!
