### ISSUE TITLE
Suggestion: Starters/Watchlist/Bookmark Category?

### ISSUE THREAD

**Issue by immortaljackal** [blackjackkent/RPThreadTrackerV3.FrontEnd#39]
Would it be possible to get another category (as in 'your turn', 'their turn', 'queued', etc.) specifically for open starters that maybe acts similar to the archive so that you can easily keep track of the threads without necessarily having it pop up in the 'to do' list whenever it gets reblogged?

Obviously I can't speak for everyone, but this would be exceptionally useful for me due to memory issues resulting from a brain injury. I've come to rely on the Tracker to essentially bookmark my open threads as much as to help me remember who I owe replies to. I know that open starters aren't cleanly tracked to begin with, since anytime anyone new interacts with it it will throw things off (especially if you're like me and keep forgetting to break them into their own independent threads), so being able to have a watchlist/bookmark option for them would be useful.

For now, I've been making do by tagging everything as being an open starter (whether or my own or replying to someone else's), but it gets messy if they're left in the turns tracking, and people misunderstand if you toss them into the queue (and again, still gets messy when people reply). Dumping them in the archive works, of course, especially when filtering it down to just the tag, but without a way to exclude a tag, it also gets cluttered quickly if you have a lot of starter threads available.

Thank you for your consideration, and all the hard work you've done on making this!
-- Lex

**Comment by blackjackkent** [comment]
Hmm. This is an interesting idea; I'll have to give it some thought and it probably won't be an addition for the initial release of the redesign, but I would definitely like to come up with a good way to handle open starters so I will definitely hold onto this suggestion for my feature updates coming afterwards.

Thank you for the idea! :)
