### ISSUE TITLE
Adding a Character

### ISSUE THREAD

**Issue by myricds** [blackjackkent/RPThreadTrackerV3.FrontEnd#42]
I've noticed an issue with the "Add Character" button. It seems to save the character most of the time, but on some occasions, the wheel will continue to spin as if updating. If I reload the page - even if after several minutes have passed - the new character will not be there. However, if I navigate to a different part of the tracker, and then back to the Characters page, in some cases it will have duplicated the new character. On one such occasion, it created four of the same character.

**Comment by blackjackkent** [comment]
Hmm. I've heard a report of this with creating threads too and am entirely unable to reproduce it myself. Is there any consistency as to when this happens? (i.e. creating a character with/without a name? doing something specific while creating the character?) Any info you can provide would be very helpful.
