### ISSUE TITLE
Deleting Threads

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#45]
So I'm deleting threads by picking my desired tracking partner and then deleting the thread(s). It does the whole refreshing thing and reset the 'tracked partner' tab back to 'show all' but it shows nothing. It looks like I've deleted all my threads, but only when I hit the actual refresh button on my browser does it show all my posts. It's happened every time I've done the deleting by partner.

**Comment by blackjackkent** [comment]
Aha. Good catch. Not 100% sure what's causing this but I will definitely look into getting it sorted out; thank you! :)
