### ISSUE TITLE
Password Reset Token Invalid/Unable to Log in

### ISSUE THREAD

**Issue by AgentViii** [blackjackkent/RPThreadTrackerV3.FrontEnd#5]
Agent 8 
I was unable to log in using my existing account. When I made an attempt to change my password, the token key would come up as invalid and prompted me to request a new one. I tried multiple times and received the same results.

I know my password is correct, because when I would try to log in with the other RPThreadTracker it would work.

**Comment by blackjackkent** [comment]
Interesting -- I'm having trouble reproducing this issue. Since it relates to your account information I will reach out to you by email about it. Thanks!

**Comment by blackjackkent** [comment]
Closing this ticket as it appears to be an account-specific issue and is being addressed by email.
