### ISSUE TITLE
Last post date missing from Archived

### ISSUE THREAD

**Issue by fibifibita** [blackjackkent/RPThreadTrackerV3.FrontEnd#6]
fibifibita
175662097671 (one of them)

pretty sure this isn't an issue but a design decision but i thought of putting it here just in case.
i normally archive threads after a month and then when 2 months have happened I remove them entirely. the last post date really helps out with this and i miss it on the archived. 

again, i'm sure this is a design decision but i thought of putting it out here in case someone else liked the feature / used it.

cheers!

**Comment by blackjackkent** [comment]
Hmm. Good to know -- I'm definitely looking for opinions on design decisions as well. :) 

I'm going to be putting together an overall survey for beta testers sometime during the beta period to get overall opinions on ideas which individual testers have put forward, so I will add this to that survey. :) Thank you!
