### ISSUE TITLE
Menu Bar Adaptability

### ISSUE THREAD

**Issue by Siriuslychessi** [blackjackkent/RPThreadTrackerV3.FrontEnd#9]
The menu bar moves as you expands the window, but the more you expand it the buttons kind of mess up. The 3 bars to expand the side bar menu hide behind the title of the page, and I was going to comment that it needed buttons for "add threads" or "add characters" because they hide when the window is not as big, and it wouldn't occur to me to click the little arrow in the top right corner for the drop down menu, it seems a "complicated" way when before you had it perfectly clear in the previous version.

(Hope this made sense, if not there are pictures bellow of the change)

![screen shot 2018-07-10 at 22 27 04](https://user-images.githubusercontent.com/41085933/42535720-6f6a9ffa-8490-11e8-9fc2-4ab1d470b979.png)
![screen shot 2018-07-10 at 22 27 19](https://user-images.githubusercontent.com/41085933/42535721-6fb1df6e-8490-11e8-8bda-50169f10ae82.png)

**Comment by blackjackkent** [comment]
Hmm, yes, you're right -- eventually in the smallest mobile view they need to be hidden in a menu but I'm probably cutting them off too soon as the screen gets smaller and they could still be shown in that mid-size screen. I will work on an update for this. :) Thanks for the feedback!

**Comment by blackjackkent** [comment]
I have updated the design so the header buttons are visible on all but the smallest (mobile phone) screen size. Let me know if this seems more usable! :)

**Comment by Siriuslychessi** [comment]
It works great now, no button gets on top of the other (both mobile and desktop) and is easier to access them :)
